"""CI / GitHub Step Summary & PR Comment Formatter.

Generates rich GitHub-flavored Markdown for:
- GitHub Actions Step Summary ($GITHUB_STEP_SUMMARY)
- Pull Request / Issue comment markdown (--output-markdown)
- CI/CD build logs and artifacts
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from driftsentry.core.models import DriftItem, DriftResult, DriftSeverity, DriftType

SEVERITY_EMOJI: dict[DriftSeverity, str] = {
    DriftSeverity.CRITICAL: "🔴",
    DriftSeverity.HIGH: "🟠",
    DriftSeverity.MEDIUM: "🟡",
    DriftSeverity.LOW: "🟢",
    DriftSeverity.INFO: "🔵",
}

DRIFT_TYPE_EMOJI: dict[DriftType, str] = {
    DriftType.CHANGED: "📝",
    DriftType.DELETED: "🗑️",
    DriftType.UNMANAGED: "👻",
}


class CISummaryFormatter:
    """Renders drift scan results as rich GitHub Markdown with collapsible details."""

    def render(
        self,
        result: DriftResult,
        fail_on: str = "any",
        failed: bool = False,
        output_path: str | Path | None = None,
    ) -> str:
        """Generate GitHub Actions Step Summary and PR comment Markdown."""
        lines: list[str] = []

        # 1. Header & Status Banner
        if failed:
            lines.append("# 🛡️ DriftSentry CI Check: Drift Detected ❌")
            lines.append("")
            lines.append(
                f"> **Status:** 🚨 Drift detected matching failure policy (`--fail-on {fail_on}`)."
            )
        elif result.has_drift:
            lines.append("# 🛡️ DriftSentry CI Check: Drift Detected (Non-Blocking) ⚠️")
            lines.append("")
            lines.append(
                f"> **Status:** ⚠️ Drift detected, but below failure threshold (`--fail-on {fail_on}`)."
            )
        else:
            lines.append("# 🛡️ DriftSentry CI Check: Clean ✅")
            lines.append("")
            lines.append(
                "> **Status:** ✅ All infrastructure resources match their desired IaC state."
            )

        lines.append("")

        # 2. Metadata Table
        lines.append("### Run Overview")
        lines.append("")
        lines.append(
            "| Scan ID | IaC Tool | Provider | Target Region(s) | Accounts | State Source | Duration |"
        )
        lines.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")

        regions_str = ", ".join(result.regions) if result.regions else (result.region or "default")
        accounts_str = ", ".join(result.accounts) if result.accounts else "default"
        state_source_display = self._truncate(result.state_source, 45)

        lines.append(
            f"| `{result.scan_id}` | {result.iac_tool.value.capitalize()} | "
            f"{result.provider.upper()} | `{regions_str}` | `{accounts_str}` | "
            f"`{state_source_display}` | {result.duration_seconds:.2f}s |"
        )
        lines.append("")

        # 3. High-Level Summary Metrics
        lines.append("### Summary")
        lines.append("")
        lines.append("| Metric | Count | Status |")
        lines.append("| :--- | :---: | :--- |")
        lines.append(f"| 📦 Total Managed Resources | {result.total_resources} | In State |")
        lines.append(f"| ☁️ Total Cloud Resources | {result.total_cloud_resources} | Discovered |")

        changed_status = (
            "✅ Clean" if result.changed_count == 0 else f"⚠️ {result.changed_count} changed"
        )
        deleted_status = (
            "✅ None" if result.deleted_count == 0 else f"🚨 {result.deleted_count} deleted"
        )
        unmanaged_status = (
            "✅ None" if result.unmanaged_count == 0 else f"👻 {result.unmanaged_count} unmanaged"
        )
        critical_status = (
            "✅ None" if result.critical_count == 0 else f"🔴 {result.critical_count} critical"
        )

        lines.append(f"| 📝 Changed Resources | {result.changed_count} | {changed_status} |")
        lines.append(f"| 🗑️ Deleted Resources | {result.deleted_count} | {deleted_status} |")
        lines.append(f"| 👻 Unmanaged Resources | {result.unmanaged_count} | {unmanaged_status} |")
        lines.append(f"| 🔴 Critical Severity | {result.critical_count} | {critical_status} |")
        lines.append("")

        if not result.has_drift:
            lines.append(
                "🎉 **No infrastructure drift detected.** Cloud resources are in full sync with IaC."
            )
            lines.append("")
            lines.append("---")
            lines.append(
                "*Generated by [DriftSentry](https://github.com/hemanthkp98/driftsentry) • Automated IaC Drift Detection*"
            )
            return self._finalize(lines, output_path)

        # 4. Table of Drifted Resources
        show_account = len(result.accounts) > 1 or any(
            (item.account_name or item.account_id) for item in result.drift_items
        )
        show_region = len(result.regions) > 1 or any(item.region for item in result.drift_items)

        lines.append(f"### Drifted Resources ({result.total_drifted})")
        lines.append("")

        header_cols = []
        divider_cols = []
        if show_account:
            header_cols.append("Account")
            divider_cols.append(":---")
        if show_region:
            header_cols.append("Region")
            divider_cols.append(":---")

        header_cols.extend(["Resource", "Type", "Severity", "Diffs", "Attributed Culprit"])
        divider_cols.extend([":---", ":---", ":---", ":---:", ":---"])

        lines.append("| " + " | ".join(header_cols) + " |")
        lines.append("| " + " | ".join(divider_cols) + " |")

        for item in result.drift_items:
            emoji = SEVERITY_EMOJI.get(item.severity, "")
            type_emoji = DRIFT_TYPE_EMOJI.get(item.drift_type, "")
            changes = str(len(item.attribute_diffs)) if item.attribute_diffs else "-"

            culprit = "-"
            if item.attribution and item.attribution.principal:
                actor = item.attribution.principal
                # Shorten long IAM ARNs
                if actor.startswith("arn:aws:iam::"):
                    actor = actor.split("/")[-1]
                clickops = " 🖱️ ClickOps" if item.attribution.is_console_change else ""
                culprit = f"`{actor}`{clickops}"

            row = []
            if show_account:
                row.append(f"`{item.account_name or item.account_id or '-'}`")
            if show_region:
                row.append(f"`{item.region or '-'}`")

            row.extend(
                [
                    f"`{item.resource_address}`",
                    f"{type_emoji} `{item.drift_type.value}`",
                    f"{emoji} `{item.severity.value}`",
                    changes,
                    culprit,
                ]
            )
            lines.append("| " + " | ".join(row) + " |")

        lines.append("")

        # 5. Collapsible <details><summary> Details for each item
        lines.append("### Detailed Attribute Diffs & Attribution")
        lines.append("")

        for item in result.drift_items:
            lines.extend(self._render_item_details(item))
            lines.append("")

        # 6. Warnings
        if result.errors:
            lines.append("<details>")
            lines.append(f"<summary>⚠️ <b>Scan Warnings ({len(result.errors)})</b></summary>")
            lines.append("")
            for error in result.errors:
                lines.append(f"- ⚠️ {error}")
            lines.append("")
            lines.append("</details>")
            lines.append("")

        # 7. Footer
        lines.append("---")
        lines.append(
            "*Generated by [DriftSentry](https://github.com/hemanthkp98/driftsentry) • Automated IaC Drift Detection*"
        )

        return self._finalize(lines, output_path)

    def _render_item_details(self, item: DriftItem) -> list[str]:
        """Render a collapsible <details><summary> block for a single drifted resource."""
        lines: list[str] = []
        emoji = SEVERITY_EMOJI.get(item.severity, "")
        type_emoji = DRIFT_TYPE_EMOJI.get(item.drift_type, "")

        summary_title = (
            f"{emoji} {type_emoji} <b><code>{item.resource_address}</code></b> "
            f"({item.drift_type.value} • {item.severity.value})"
        )

        lines.append("<details>")
        lines.append(f"<summary>{summary_title}</summary>")
        lines.append("")
        lines.append(f"- **Resource Address:** `{item.resource_address}`")
        lines.append(f"- **Resource Type:** `{item.resource_type}`")
        if item.resource_id:
            lines.append(f"- **Cloud Resource ID:** `{item.resource_id}`")
        if item.region:
            lines.append(f"- **Region:** `{item.region}`")
        if item.account_name or item.account_id:
            lines.append(f"- **Account:** `{item.account_name or item.account_id}`")

        # Attribute diffs
        if item.attribute_diffs:
            lines.append("")
            lines.append("#### Attribute Differences")
            lines.append("")
            lines.append("| Attribute | Desired (IaC State) | Actual (Live Cloud) |")
            lines.append("| :--- | :--- | :--- |")
            for diff in item.attribute_diffs:
                desired = self._format_value(diff.desired_value)
                actual = self._format_value(diff.actual_value)
                lines.append(f"| `{diff.path}` | `{desired}` | `{actual}` |")

        elif item.drift_type == DriftType.DELETED:
            lines.append("")
            lines.append(
                "> 🗑️ **Deleted Resource:** This resource is recorded in state but was not found in the live cloud provider."
            )

        elif item.drift_type == DriftType.UNMANAGED:
            lines.append("")
            lines.append(
                "> 👻 **Unmanaged Resource (Shadow IT):** This resource exists in the live cloud provider but is not tracked in any IaC state file."
            )
            if item.cloud_resource and item.cloud_resource.tags:
                lines.append("")
                lines.append("**Live Tags:**")
                lines.append("```json")
                import json

                lines.append(json.dumps(item.cloud_resource.tags, indent=2))
                lines.append("```")

        # Attribution
        if item.attribution and (item.attribution.principal or item.attribution.event_name):
            lines.append("")
            lines.append("#### CloudTrail Attribution")
            lines.append("")
            lines.append(f"> - **IAM Principal:** `{item.attribution.principal or 'Unknown'}`")
            lines.append(f"> - **Event Name:** `{item.attribution.event_name or 'N/A'}`")
            lines.append(
                f"> - **Event Time:** `{item.attribution.event_time.isoformat() if item.attribution.event_time else 'N/A'}`"
            )
            clickops_str = (
                "Yes ⚠️ (AWS Management Console)"
                if item.attribution.is_console_change
                else "No (API / CLI / Automation)"
            )
            lines.append(f"> - **Console Change (ClickOps):** {clickops_str}")
            if item.attribution.source_ip:
                lines.append(f"> - **Source IP:** `{item.attribution.source_ip}`")
            if item.attribution.user_agent:
                lines.append(
                    f"> - **User Agent:** `{self._truncate(item.attribution.user_agent, 60)}`"
                )

        lines.append("")
        lines.append("</details>")
        return lines

    def render_error(
        self,
        error_message: str,
        output_path: str | Path | None = None,
    ) -> str:
        """Render a GitHub Actions Step Summary for an operational or scanning error."""
        lines: list[str] = [
            "# 🛡️ DriftSentry CI Check: Error ❌",
            "",
            "> **Status:** 🚨 DriftSentry encountered an error while scanning infrastructure.",
            "",
            "### Error Details",
            "",
            "```",
            error_message.strip(),
            "```",
            "",
            "---",
            "*Generated by [DriftSentry](https://github.com/hemanthkp98/driftsentry) • Automated IaC Drift Detection*",
        ]
        return self._finalize(lines, output_path)

    def _finalize(self, lines: list[str], output_path: str | Path | None) -> str:
        md = "\n".join(lines)
        if output_path:
            path = Path(output_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(md, encoding="utf-8")
        return md

    @staticmethod
    def _truncate(text: str, max_len: int) -> str:
        if len(text) <= max_len:
            return text
        return text[: max_len - 3] + "..."

    @staticmethod
    def _format_value(value: Any) -> str:
        if value is None:
            return "null"
        val_str = str(value).replace("\n", " ").replace("|", "\\|")
        if len(val_str) > 60:
            return val_str[:57] + "..."
        return val_str


def write_step_summary(
    content: str,
    step_summary_path: str | Path | None = None,
) -> Path | None:
    """Write or append markdown content to the GitHub Actions Step Summary file.

    If step_summary_path is not specified, auto-detects $GITHUB_STEP_SUMMARY.
    Returns the Path written to, or None if no step summary path is configured.
    """
    target: str | None = (
        str(step_summary_path) if step_summary_path else os.environ.get("GITHUB_STEP_SUMMARY")
    )

    if not target or not target.strip():
        return None

    path = Path(target)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(content.rstrip() + "\n\n")

    return path
